<?php
defined('_JEXEC') or die;
?>
<style>
.rumax-admin,.rumax-admin *{color:#172033}
.rumax-admin{max-width:1460px;margin:20px auto;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033!important}
.rumax-admin *{box-sizing:border-box}.rumax-admin h1{font-size:29px;margin:0 0 5px}.rumax-admin h2{font-size:20px;margin:0 0 12px}.rumax-admin h3{font-size:15px;margin:20px 0 8px}
.rumax-admin .rumax-subtitle{color:#667085;margin:0 0 20px}.rumax-layout{display:grid;grid-template-columns:225px 1fr;gap:18px}
.rumax-nav{background:#111827;border-radius:14px;padding:10px;align-self:start;position:sticky;top:18px}.rumax-nav a{display:block;color:#d1d5db!important;text-decoration:none;padding:10px 12px;border-radius:9px;font-size:13px;margin:2px 0}.rumax-nav a:hover,.rumax-nav a.active{background:#4f46e5;color:#fff!important}
.rumax-main{min-width:0}.rumax-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:21px;margin-bottom:16px;box-shadow:0 3px 12px rgba(15,23,42,.04)}
.rumax-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.rumax-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}
.rumax-field{display:flex;flex-direction:column;gap:6px}.rumax-field label{font-size:12px;font-weight:700;color:#344054!important}.rumax-field small,.rumax-help{font-size:12px;color:#667085!important}
.rumax-field input[type=text],.rumax-field input[type=password],.rumax-field input[type=number],.rumax-field input[type=url],.rumax-field input[type=email],.rumax-field input[type=datetime-local],.rumax-field select,.rumax-field textarea{width:100%;border:1px solid #d0d5dd;border-radius:8px;padding:9px 10px;background:#fff!important;color:#101828!important;text-shadow:none}.rumax-field textarea{min-height:105px;resize:vertical}
.rumax-check{display:flex;align-items:center;gap:8px;font-size:13px;margin:7px 0;color:#172033!important}.rumax-check input{width:16px;height:16px}.rumax-actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.rumax-button{border:0;border-radius:8px;background:#4f46e5;color:#fff!important;padding:10px 15px;font-weight:650;cursor:pointer}.rumax-button.secondary{background:#eef2ff;color:#3730a3!important}.rumax-button.danger{background:#dc2626;color:#fff!important}.rumax-status{font-size:13px;color:#087443!important}
.rumax-table{width:100%;border-collapse:collapse;font-size:13px}.rumax-table th,.rumax-table td{padding:9px;border-bottom:1px solid #eef0f3;text-align:left;vertical-align:top}.rumax-table th{color:#667085;font-size:11px;text-transform:uppercase;letter-spacing:.04em}.rumax-code{font-family:ui-monospace,monospace;font-size:11px;white-space:pre-wrap;max-width:480px;word-break:break-word}
.rumax-chip{display:inline-block;background:#eef2ff;color:#3730a3!important;border-radius:99px;padding:3px 8px;font-size:11px}.rumax-note{padding:12px 14px;border-radius:9px;background:#f8fafc;color:#475467!important;font-size:13px}.rumax-brand{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}
@media(max-width:900px){.rumax-layout{grid-template-columns:1fr}.rumax-nav{position:static;display:flex;overflow:auto;gap:4px}.rumax-nav a{white-space:nowrap}.rumax-grid,.rumax-grid.three{grid-template-columns:1fr}}
</style>
<div class="rumax-admin">
  <div class="rumax-brand"><div><h1>Ru-max для Joomla</h1><p class="rumax-subtitle">Интеграция Joomla с MAX — публикации, уведомления, автопостинг, виджет и живой чат.</p></div><span class="rumax-chip">v1.0.2 Joomla</span></div>
  <form method="post" action="index.php?option=com_rumax">
    <input type="hidden" name="task" value="save"><input type="hidden" name="tab" value="<?php echo htmlspecialchars($tab, ENT_QUOTES, 'UTF-8'); ?>"><?php echo $tokenHtml; ?>
    <div class="rumax-layout">
      <nav class="rumax-nav">
        <?php $tabs = ['main'=>'Главная','publications'=>'Отправка публикаций','notifications'=>'Личные уведомления','extra'=>'Дополнительные','autopost'=>'Автопостинг','widget'=>'Чат-виджет','contacts'=>'Связь с клиентами','social'=>'Социальные сети','direct'=>'Прямой доступ','settings'=>'Настройки','history'=>'История','instructions'=>'Инструкция','updates'=>'Обновления','activation'=>'Активация']; foreach ($tabs as $key=>$label): ?>
          <a class="<?php echo $tab === $key ? 'active' : ''; ?>" href="index.php?option=com_rumax&tab=<?php echo $key; ?>"><?php echo $label; ?></a>
        <?php endforeach; ?>
      </nav>
      <main class="rumax-main">
        <?php if ($tab === 'main'): ?>
        <section class="rumax-card"><h2>Подключение MAX</h2><p class="rumax-note">Получите токен в <a href="https://business.max.ru" target="_blank" rel="noopener">business.max.ru</a>, затем укажите каналы или группы, куда плагин будет отправлять сообщения.</p><div class="rumax-grid" style="margin-top:16px"><div class="rumax-field"><label>Токен бота MAX</label><input type="password" name="settings[bot_token]" value="<?php echo htmlspecialchars($settings['bot_token'], ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"></div><div class="rumax-field"><label>Имя бота</label><input type="text" name="settings[bot_name]" value="<?php echo htmlspecialchars($settings['bot_name'], ENT_QUOTES, 'UTF-8'); ?>"></div></div><h3>Каналы MAX</h3><div class="rumax-grid"><div class="rumax-field"><label>ID канала или группы</label><input type="text" name="settings[channels][0][id]" value="<?php echo htmlspecialchars($settings['channels'][0]['id'] ?? '', ENT_QUOTES, 'UTF-8'); ?>" placeholder="@channel или числовой ID"></div><div class="rumax-field"><label>Название канала</label><input type="text" name="settings[channels][0][name]" value="<?php echo htmlspecialchars($settings['channels'][0]['name'] ?? '', ENT_QUOTES, 'UTF-8'); ?>"></div></div><div class="rumax-actions" style="margin-top:16px"><button class="rumax-button secondary" type="button" data-rumax-action="test_connection">Проверить подключение</button><span class="rumax-status" data-rumax-status></span></div></section>
        <?php elseif ($tab === 'publications'): ?>
        <section class="rumax-card"><h2>Отправка публикаций</h2><label class="rumax-check"><input type="checkbox" name="settings[post_sender_enabled]" value="1" <?php echo !empty($settings['post_sender_enabled']) ? 'checked' : ''; ?>> Включить автоматическую отправку материалов в MAX</label><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="settings[send_new_post]" value="1" <?php echo !empty($settings['send_new_post']) ? 'checked' : ''; ?>> Отправлять новые материалы</label><label class="rumax-check"><input type="checkbox" name="settings[send_updated_post]" value="1" <?php echo !empty($settings['send_updated_post']) ? 'checked' : ''; ?>> Отправлять обновлённые материалы</label><label class="rumax-check"><input type="checkbox" name="settings[show_read_more]" value="1" <?php echo !empty($settings['show_read_more']) ? 'checked' : ''; ?>> Добавлять ссылку «Читать далее»</label></div><div class="rumax-grid three"><div class="rumax-field"><label>Задержка отправки, секунд</label><input type="number" min="0" max="300" name="settings[send_delay_seconds]" value="<?php echo (int)$settings['send_delay_seconds']; ?>"></div><div class="rumax-field"><label>Повторных попыток</label><input type="number" min="0" max="10" name="settings[retry_count]" value="<?php echo (int)$settings['retry_count']; ?>"></div><div class="rumax-field"><label>Лимит изображения, МБ</label><input type="number" min="1" max="50" name="settings[image_size_limit_mb]" value="<?php echo (int)$settings['image_size_limit_mb']; ?>"></div></div><div class="rumax-field" style="margin-top:16px"><label>Шаблон публикации</label><textarea name="settings[post_template]"><?php echo htmlspecialchars($settings['post_template'] ?? "{title}\n\n{excerpt}\n{url}", ENT_QUOTES, 'UTF-8'); ?></textarea><small>Доступны: {title}, {excerpt}, {text}, {url}, {image}</small></div></section>
        <?php elseif ($tab === 'notifications'): ?>
        <section class="rumax-card"><h2>Личные уведомления</h2><label class="rumax-check"><input type="checkbox" name="settings[notifications_enabled]" value="1" <?php echo !empty($settings['notifications_enabled']) ? 'checked' : ''; ?>> Дублировать уведомления Joomla и расширений в личный чат MAX</label><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="settings[notify_user_registration]" value="1" <?php echo !empty($settings['notify_user_registration']) ? 'checked' : ''; ?>> Регистрация пользователя</label><label class="rumax-check"><input type="checkbox" name="settings[notify_customer_order]" value="1" <?php echo !empty($settings['notify_customer_order']) ? 'checked' : ''; ?>> Уведомления о заказах</label></div><div class="rumax-field"><label>Шаблон уведомления</label><textarea name="settings[notify_template]"><?php echo htmlspecialchars($settings['notify_template'], ENT_QUOTES, 'UTF-8'); ?></textarea><small>Доступны: {email_subject}, {email_message}, {site_name}</small></div><div class="rumax-field"><label>Чаты получателей через запятую</label><input type="text" name="settings[notify_chat_ids]" value="<?php echo htmlspecialchars(implode(',', (array)$settings['notify_chat_ids']), ENT_QUOTES, 'UTF-8'); ?>"></div></section>
        <?php elseif ($tab === 'widget'): ?>
        <section class="rumax-card"><h2>Чат-виджет MAX</h2><label class="rumax-check"><input type="checkbox" name="settings[chat_widget_enabled]" value="1" <?php echo !empty($settings['chat_widget_enabled']) ? 'checked' : ''; ?>> Показывать плавающий виджет</label><div class="rumax-grid three"><div class="rumax-field"><label>Ссылка чата</label><input type="url" name="settings[chat_widget_url]" value="<?php echo htmlspecialchars($settings['chat_widget_url'], ENT_QUOTES, 'UTF-8'); ?>" placeholder="https://max.ru/..."></div><div class="rumax-field"><label>Размер</label><select name="settings[chat_widget_size]"><?php foreach(['small'=>'Маленький','medium'=>'Средний','large'=>'Большой'] as $v=>$l): ?><option value="<?php echo $v; ?>" <?php echo $settings['chat_widget_size']===$v?'selected':''; ?>><?php echo $l; ?></option><?php endforeach; ?></select></div><div class="rumax-field"><label>Положение</label><select name="settings[chat_widget_position]"><option value="right" <?php echo $settings['chat_widget_position']==='right'?'selected':''; ?>>Справа</option><option value="left" <?php echo $settings['chat_widget_position']==='left'?'selected':''; ?>>Слева</option></select></div></div><div class="rumax-grid three" style="margin-top:16px"><div class="rumax-field"><label>Отступ снизу, px</label><input type="number" min="0" max="300" name="settings[chat_widget_bottom_offset]" value="<?php echo (int)$settings['chat_widget_bottom_offset']; ?>"></div><div class="rumax-field"><label>Задержка показа, сек</label><input type="number" min="0" max="300" name="settings[chat_widget_show_delay]" value="<?php echo (int)$settings['chat_widget_show_delay']; ?>"></div><div class="rumax-field"><label>Анимация</label><select name="settings[chat_widget_animation]"><?php foreach(['none'=>'Нет','pulse'=>'Пульсация','ripple'=>'Рябь','bounce'=>'Подпрыгивание','shake'=>'Встряска','glow'=>'Свечение','rotate'=>'Вращение','float'=>'Левитация','pendulum'=>'Маятник','burst'=>'Взрыв','heartbeat'=>'Сердцебиение'] as $v=>$l): ?><option value="<?php echo $v; ?>" <?php echo $settings['chat_widget_animation']===$v?'selected':''; ?>><?php echo $l; ?></option><?php endforeach; ?></select></div></div><div class="rumax-field" style="margin-top:16px"><label>Приветствие</label><textarea name="settings[chat_widget_message]"><?php echo htmlspecialchars($settings['chat_widget_message'], ENT_QUOTES, 'UTF-8'); ?></textarea></div><label class="rumax-check"><input type="checkbox" name="settings[chat_widget_message_enabled]" value="1" <?php echo !empty($settings['chat_widget_message_enabled'])?'checked':''; ?>> Показывать приветственное сообщение</label><label class="rumax-check"><input type="checkbox" name="settings[chat_widget_retention_enabled]" value="1" <?php echo !empty($settings['chat_widget_retention_enabled'])?'checked':''; ?>> Показывать окно удержания при закрытии</label></section>
        <?php elseif ($tab === 'contacts'): ?>
        <section class="rumax-card"><h2>Связь с клиентами</h2><label class="rumax-check"><input type="checkbox" name="pro[enabled]" value="1" <?php echo !empty($pro['enabled'])?'checked':''; ?>> Включить мультиканальное меню</label><div class="rumax-grid"><div class="rumax-field"><label>MAX-чат для заявок</label><input type="text" name="pro[chat][target]" value="<?php echo htmlspecialchars($pro['chat']['target'], ENT_QUOTES, 'UTF-8'); ?>"></div><div class="rumax-field"><label>Заголовок живого чата</label><input type="text" name="pro[chat][title]" value="<?php echo htmlspecialchars($pro['chat']['title'], ENT_QUOTES, 'UTF-8'); ?>"></div></div><h3>Каналы</h3><?php foreach ($pro['channels'] as $key=>$channel): ?><div class="rumax-grid" style="margin-bottom:8px"><label class="rumax-check"><input type="checkbox" name="pro[channels][<?php echo $key; ?>][enabled]" value="1" <?php echo !empty($channel['enabled'])?'checked':''; ?>> <?php echo htmlspecialchars(ucfirst($key), ENT_QUOTES, 'UTF-8'); ?></label><div class="rumax-field"><input type="text" name="pro[channels][<?php echo $key; ?>][value]" value="<?php echo htmlspecialchars($channel['value'] ?? '', ENT_QUOTES, 'UTF-8'); ?>" placeholder="Ссылка, телефон или email"></div></div><?php endforeach; ?><div class="rumax-grid three"><div class="rumax-field"><label>Цвет иконки</label><input type="text" name="pro[style][icon_background]" value="<?php echo htmlspecialchars($pro['style']['icon_background'], ENT_QUOTES, 'UTF-8'); ?>"></div><div class="rumax-field"><label>Цвет текста</label><input type="text" name="pro[style][icon_color]" value="<?php echo htmlspecialchars($pro['style']['icon_color'], ENT_QUOTES, 'UTF-8'); ?>"></div><div class="rumax-field"><label>Компоновка</label><select name="pro[style][layout]"><?php foreach(['circle'=>'Круг','grid'=>'Сетка','menu'=>'Строка'] as $v=>$l): ?><option value="<?php echo $v; ?>" <?php echo $pro['style']['layout']===$v?'selected':''; ?>><?php echo $l; ?></option><?php endforeach; ?></select></div></div></section>
        <?php elseif ($tab === 'social'): ?>
        <section class="rumax-card"><h2>Социальные сети</h2><div class="rumax-note">Параметры сохраняются в настройках расширения. Токены не выводятся в журнал и передаются только на официальный API выбранной сети.</div><h3>Telegram</h3><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="social[telegram_enabled]" value="1" <?php echo !empty($social['telegram_enabled'])?'checked':''; ?>> Включить Telegram</label><div class="rumax-field"><label>Bot token</label><input type="password" name="social[telegram_bots][0][token]" value="<?php echo htmlspecialchars($social['telegram_bots'][0]['token'] ?? '', ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"></div><div class="rumax-field"><label>Chat ID</label><input type="text" name="social[telegram_bots][0][chat_id]" value="<?php echo htmlspecialchars($social['telegram_bots'][0]['chat_id'] ?? '', ENT_QUOTES, 'UTF-8'); ?>"></div></div><h3>ВКонтакте</h3><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="social[vk_enabled]" value="1" <?php echo !empty($social['vk_enabled'])?'checked':''; ?>> Включить ВКонтакте</label><div class="rumax-field"><label>ID группы / владельца</label><input type="text" name="social[vk_owner_id]" value="<?php echo htmlspecialchars($social['vk_owner_id'], ENT_QUOTES, 'UTF-8'); ?>"></div><div class="rumax-field"><label>Community Access Token</label><input type="password" name="social[vk_access_token]" value="<?php echo htmlspecialchars($social['vk_access_token'], ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"></div></div><h3>Одноклассники и Дзен</h3><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="social[ok_enabled]" value="1" <?php echo !empty($social['ok_enabled'])?'checked':''; ?>> Включить OK</label><div class="rumax-field"><label>OK access token</label><input type="password" name="social[ok_access_token]" value="<?php echo htmlspecialchars($social['ok_access_token'], ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"></div><label class="rumax-check"><input type="checkbox" name="social[dzen_enabled]" value="1" <?php echo !empty($social['dzen_enabled'])?'checked':''; ?>> Включить Яндекс Дзен</label><div class="rumax-field"><label>Dzen channel ID</label><input type="text" name="social[dzen_channel_id]" value="<?php echo htmlspecialchars($social['dzen_channel_id'], ENT_QUOTES, 'UTF-8'); ?>"></div></div></section>
        <?php elseif ($tab === 'direct'): ?>
        <section class="rumax-card"><h2>Прямой доступ</h2><p class="rumax-help">Отправьте произвольный текст в первый настроенный канал MAX.</p><div class="rumax-field"><label>Текст сообщения</label><textarea id="rumax-push-message" placeholder="Введите сообщение"></textarea></div><button class="rumax-button" type="button" data-rumax-action="send_push">Отправить в MAX</button><span class="rumax-status" data-rumax-status></span></section>
        <?php elseif ($tab === 'history'): ?>
        <section class="rumax-card"><div class="rumax-brand"><h2>История и журнал</h2><button class="rumax-button danger" type="button" data-rumax-action="clear_logs">Очистить журнал</button></div><table class="rumax-table"><thead><tr><th>Время</th><th>Тип</th><th>Статус</th><th>Событие</th><th>Детали</th></tr></thead><tbody><?php foreach ($history as $row): ?><tr><td><?php echo htmlspecialchars($row->event_time, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($row->event_type, ENT_QUOTES, 'UTF-8'); ?></td><td><span class="rumax-chip"><?php echo htmlspecialchars($row->status, ENT_QUOTES, 'UTF-8'); ?></span></td><td><?php echo htmlspecialchars($row->event_data, ENT_QUOTES, 'UTF-8'); ?></td><td class="rumax-code"><?php echo htmlspecialchars($row->details, ENT_QUOTES, 'UTF-8'); ?></td></tr><?php endforeach; ?></tbody></table></section>
        <?php elseif ($tab === 'autopost'): ?>
        <section class="rumax-card"><div class="rumax-brand"><div><h2>Очередь автопостинга</h2><p class="rumax-help">Очередь обрабатывается при посещении сайта и кнопкой ниже. Для cron используйте URL планировщика Joomla.</p></div><button class="rumax-button secondary" type="button" data-rumax-action="process_queue">Обработать очередь сейчас</button></div><table class="rumax-table"><thead><tr><th>Когда</th><th>Сеть</th><th>Материал</th><th>Статус</th><th>Попытки</th><th>Ошибка</th></tr></thead><tbody><?php foreach ($queue as $row): ?><tr><td><?php echo htmlspecialchars($row->due_at, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($row->network, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int)$row->content_id; ?></td><td><?php echo htmlspecialchars($row->status, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int)$row->attempts; ?></td><td><?php echo htmlspecialchars($row->last_error, ENT_QUOTES, 'UTF-8'); ?></td></tr><?php endforeach; ?></tbody></table></section>
        <?php elseif ($tab === 'instructions'): ?>
        <section class="rumax-card"><h2>Инструкция</h2><div class="rumax-note"><p><b>1.</b> Создайте бота и получите токен на business.max.ru.</p><p><b>2.</b> Добавьте бота в нужный канал или группу и укажите ID в разделе «Главная».</p><p><b>3.</b> Включите публикации и виджет. Для соцсетей добавьте токены на вкладке «Социальные сети».</p><p><b>4.</b> Включите контентный плагин Ru-max и системный плагин Ru-max после установки пакета.</p><p><b>5.</b> Для стабильного автопостинга добавьте cron на <code>index.php?option=com_rumax&amp;task=cron</code> с POST-токеном или запускайте обработку из админки.</p></div></section>
        <?php elseif ($tab === 'settings'): ?>
        <section class="rumax-card"><h2>Настройки</h2><div class="rumax-grid"><label class="rumax-check"><input type="checkbox" name="settings[enable_bot_api_log]" value="1" <?php echo !empty($settings['enable_bot_api_log'])?'checked':''; ?>> Вести подробный журнал API</label><label class="rumax-check"><input type="checkbox" name="settings[enable_post_sender_log]" value="1" <?php echo !empty($settings['enable_post_sender_log'])?'checked':''; ?>> Вести журнал публикаций</label><label class="rumax-check"><input type="checkbox" name="settings[share_button_enabled]" value="1" <?php echo !empty($settings['share_button_enabled'])?'checked':''; ?>> Добавлять кнопку «Поделиться в MAX» в статьи</label><label class="rumax-check"><input type="checkbox" name="settings[send_files_by_url]" value="1" <?php echo !empty($settings['send_files_by_url'])?'checked':''; ?>> Отправлять изображения по URL</label></div><div class="rumax-grid"><div class="rumax-field"><label>Ключ защищённого cron</label><input type="password" name="settings[cron_key]" value="<?php echo htmlspecialchars($settings['cron_key'] ?? '', ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"><small>После сохранения вызывайте <code>index.php?option=com_rumax&amp;task=cron&amp;key=...</code>.</small></div><div class="rumax-field"><label>Интервал повторной попытки, секунд</label><input type="number" min="5" max="3600" name="settings[retry_delay_seconds]" value="<?php echo (int)$settings['retry_delay_seconds']; ?>"></div></div></section>
        <?php elseif ($tab === 'activation'): ?>
        <section class="rumax-card"><h2>Активация</h2><p class="rumax-note">Лицензия и условия использования остаются такими же, как в исходном WP Ru-max. Укажите ключ, если он у вас есть, или обратитесь к правообладателю за лицензией для социально значимого проекта.</p><div class="rumax-field"><label>Лицензионный ключ</label><input type="password" name="settings[license_key]" value="<?php echo htmlspecialchars($settings['license_key'], ENT_QUOTES, 'UTF-8'); ?>" autocomplete="new-password"></div><p class="rumax-help">Официальный сайт: <a href="https://fixcoder.ru/" target="_blank" rel="noopener">fixcoder.ru</a></p></section>
        <?php else: ?>
        <section class="rumax-card"><h2><?php echo htmlspecialchars($tabs[$tab] ?? 'Настройки', ENT_QUOTES, 'UTF-8'); ?></h2><p class="rumax-note">Раздел подготовлен для совместимости с исходной структурой WP Ru-max. Основные параметры доступны на вкладках «Главная», «Отправка публикаций», «Личные уведомления», «Чат-виджет», «Связь с клиентами» и «Социальные сети».</p></section>
        <?php endif; ?>
        <?php if (!in_array($tab, ['history','instructions','updates'])): ?><div class="rumax-actions"><button class="rumax-button" type="submit">Сохранить настройки</button></div><?php endif; ?>
      </main>
    </div>
  </form>
</div>
<script>
(function(){
  var root=document.querySelector('.rumax-admin'), token=<?php echo json_encode($token); ?>, endpoint='index.php?option=com_rumax&task=ajax&format=json';
  root.querySelectorAll('[data-rumax-action]').forEach(function(button){
    button.addEventListener('click',function(){
      var action=button.getAttribute('data-rumax-action'), data=new FormData();
      data.append('<?php echo $token; ?>','1'); data.append('action',action);
      if(action==='test_connection') data.append('bot_token',root.querySelector('[name="settings[bot_token]"]').value);
      if(action==='send_push') data.append('message',root.querySelector('#rumax-push-message').value);
      var status=root.querySelector('[data-rumax-status]');
      fetch(endpoint,{method:'POST',body:data,credentials:'same-origin'}).then(function(r){return r.json()}).then(function(res){if(status) status.textContent=res.message||'Готово';}).catch(function(){if(status) status.textContent='Ошибка запроса';});
    });
  });
})();
</script>